# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret base_url

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

withings:
  client_id: !secret WITHINGS_CLIENT
  client_secret: !secret WITHINGS_CONSUMER_SECRET
  profiles:
    - Marcus

verisure:
  username: !secret verisureuser
  password: !secret verisurepass

sensor:
  - platform: qbittorrent
    url: !secret qbit_host
    username: !secret qbit_user
    password: !secret qbit_pass
  - platform: sonarr
    host: !secret sonarrip
    api_key: !secret sonarrAPI
    port: 443
    ssl: true
    monitored_conditions:
      - upcoming
      - series
  - platform: radarr
    host: !secret radarrip
    api_key: !secret radarrAPI
    port: 443
    ssl: true
    monitored_conditions:
      - upcoming
      - movies

spotify:
  client_id: !secret spotify_client
  client_secret: !secret spotify_secret

webostv:
  host: 10.0.50.14

pi_hole:
  - host: !secret pi_hole_url
    api_key: !secret pi_hole_api_key
    ssl: true
